services:
  api-flexicharge:
    build: .
    ports:
      - "8081:8081"
    environment:
      # Pasamos las variables del .env al contenedor
      - SPRING_DATA_MONGODB_URI=mongodb+srv://${MONGO_USER}:${MONGO_PASS}@${MONGO_CLUSTER}/${MONGO_DB}?retryWrites=true&w=majority
      - APPLICATION_SECURITY_JWT_SECRET-KEY=${JWT_SECRET}
    restart: always

  sonarqube:
    image: sonarqube:community
    container_name: sonarqube
    ports:
      - "9000:9000"
    networks:
      - sonarnet

networks:
  sonarnet: